### ISSUE TITLE
Gradient Generator

### ISSUE THREAD

**Issue by DYNAMICMORTAL** [Diptenusarkar/Website-Template#15]

**Comment by Diptenusarkar** [comment]
Hello Mihir 👋
Unfortunately, this rep doesn't have any active issue,
This is a website template, you can do one thing just create any type of template then push your pull request. That's all.
Best of luck, See you soon with your code

**Comment by Diptenusarkar** [comment]
Yaap Sure I'll do, BUT! It should be a website template or any kind of project. If you're going to just edit README.md I'm not going to accept this.

**Comment by DYNAMICMORTAL** [comment]
Thank you in advance. I would do good.

**Comment by Diptenusarkar** [comment]
Best of luck 🤞 See you soon with your Code 🧑‍💻

**Comment by DYNAMICMORTAL** [comment]
@Diptenusarkar Please add me as Contributor to this repo.

**Comment by Diptenusarkar** [comment]
You are already in. Check the contributor page. Or you can see a contributor badge on your name.

**Comment by DYNAMICMORTAL** [comment]
@Diptenusarkar Thank you
