### ISSUE TITLE
SIdebar+Navbar for Desktop and Mobile screens

### ISSUE THREAD

**Issue by taanii** [Diptenusarkar/Website-Template#191]
This template can be used for any type of website which wants a fixed left Sidebar and a Navbar. 

There are many such templates available but one issue that this template will solve is on the mobile screen. It will have two hamburger menus on left and right, one for Sidebar, other for Navbar.

It will be simple to edit, and I will be using bootstrap for this.

**Comment by Diptenusarkar** [comment]
Sure. You can Do it.

**Comment by taanii** [comment]
Thanks!
@Diptenusarkar Will my PR in this repository be considered for hacktoberfest 2022?
