### ISSUE TITLE
readme.md update

### ISSUE THREAD

**Issue by adityapathakk** [Diptenusarkar/Website-Template#21]
**Is your feature request related to a problem? Please describe.**
Since the number of templates on the site is growing, it'd be nice to have an index of all the templates in this repository shown in one place for everybody's convenience. Besides, the language can be better.

**Describe the solution you'd like**
I can work on this under a documentation label, and I wish that I get a hacktoberfest-accepted label if my work is found to be satisfactory!

**Comment by Diptenusarkar** [comment]
Hey Aditya, This is a really good idea, can you do one thing more?
To be just for this idea you will be an exception, just for documentation I'll going to add a hacktoberfest label on it. This is for you only. Another request can you create a website for that one where user can them easily? Just for that, you need to create another branch It's called gh-page.
If not this is perfectly okay, Now you can start your document writing.
Thank You & Best of luck

**Comment by adityapathakk** [comment]
Can a basic website that ONLY contains all the links work?

**Comment by Diptenusarkar** [comment]
Yapp, With some project screenshot.

**Comment by adityapathakk** [comment]
Dropped a pull request with an Index of Templates, and will do the website later!
'hacktoberfest-accepted' label would be appreciated :)
