### ISSUE TITLE
fix: css not loading properly

### ISSUE THREAD

**Issue by divyansshu** [Diptenusarkar/Website-Template#308]
![Web capture_1-10-2023_181141_127 0 0 1](https://github.com/Diptenusarkar/Website-Template/assets/120498621/21fa76fb-7352-498c-bf90-e2636e155a3f)

Css not loading properly of admin dashboard page.

**Comment by Diptenusarkar** [comment]
Sure You Can Fix This problem

**Comment by Diptenusarkar** [comment]
Can I assign you

**Comment by divyansshu** [comment]
> Can I assign you

yes

**Comment by divyansshu** [comment]
> Can I assign you

heyy @Diptenusarkar can you also add hactoberfest label on issues..😊
