### ISSUE TITLE
feat: emoji support for Approval page template

### ISSUE THREAD

**Issue by divyansshu** [Diptenusarkar/Website-Template#309]
i think it would be great if emojis are also use to describe the satisfaction in approval page template.

![Screenshot 2023-10-01 181738](https://github.com/Diptenusarkar/Website-Template/assets/120498621/75acbdee-c95f-4160-8281-fdbb137801b3)

**Comment by Diptenusarkar** [comment]
That's Cool, Go ahead.

Also Don't forget to give a star ⭐
