### ISSUE TITLE
Feat: Create Next.js Authentication Boilerplate

### ISSUE THREAD

**Issue by zainbinshakoor** [Diptenusarkar/Website-Template#311]
To provide a starting point for developers building Next.js applications that require user authentication.

User registration and login

Hacktoberfest

**Comment by Diptenusarkar** [comment]
Sure You can Do it. 
Please Don't forget to give star ⭐

**Comment by zainbinshakoor** [comment]
@Diptenusarkar  could you please assign the label of hacktoberfest for this feature?

**Comment by Diptenusarkar** [comment]
Sure I'll marg Your PR Under hacktoberfest accept label

**Comment by zainbinshakoor** [comment]
- #313
