### ISSUE TITLE
QR-code Generator 

### ISSUE THREAD

**Issue by GitPratyush** [Diptenusarkar/Website-Template#324]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I would like to add a QR-code generator in this repo.

**Comment by GitPratyush** [comment]
@Diptenusarkar  could you assign me this issue  under hacktoberfest2023.

**Comment by Diptenusarkar** [comment]
Sure I'll Add Hacktoberfest Accept label on your PR

**Comment by ujjwalshivhare** [comment]
hello sir,
can you assign me this issue

**Comment by GitPratyush** [comment]
@ujjwalshivhare i am currently working on this issue however you can create your own issue.

**Comment by Diptenusarkar** [comment]
Hello @ujjwalshivhare As You can see @GitPratyush Already Working With this Issue, Also He/she submitted his PR #330 
I Request You please open/ create your own issue then work on it. 
Thank You for Understanding.
