### ISSUE TITLE
Loading Button Animations Template 

### ISSUE THREAD

**Issue by Surya-V-28** [Diptenusarkar/Website-Template#351]
Please let me know if you find any issues 
Please assign it under the hacktober fest , i want to work under it 

**Is your feature request related to a problem? Please describe.**
sometimes we can show the user the loading instead of directly moving to other page 

**Describe the solution you'd like**
this button looks cool

**Comment by Diptenusarkar** [comment]
Submit your PR I will add hacktoberfest accept label
