### ISSUE TITLE
Overview session

### ISSUE THREAD

**Issue by jhonatasmatos** [Diptenusarkar/Website-Template#354]
**Is your feature request related to a problem? Please describe.**
I was seeing templates but some templates don't have images, so I needed to download them to see.

**Describe the solution you'd like**
I was thinking of creating a session called **Overview** (or you can suggest another name) in readme where we can add a link to see the template images and then we can add information when people add templates need to add an image and put the link in the Overview session.

I can create an Overview session, take a screenshot from projects that don't have images and organize the session.

Do you think it could be good and useful?

**Comment by Diptenusarkar** [comment]
This is a good initiative, Go for it.

**Comment by jhonatasmatos** [comment]
Hey @Diptenusarkar I already finished, I have just one question, there are 5 projects broken, Do I keep them or remove them?

They don't have one file called _tsParticles-64.png_

![image](https://github.com/Diptenusarkar/Website-Template/assets/16242029/32bcdfec-05bc-4bd1-9ddf-378ced701126)

Then the layout is broken like the image below

![image](https://github.com/Diptenusarkar/Website-Template/assets/16242029/0bcb8167-a3eb-41a0-8c08-2003c05a22ee)

What do you suggest?

**Comment by Diptenusarkar** [comment]
What if we keep them? 
Can you replace it with an appropriate image?

**Comment by jhonatasmatos** [comment]
I fixed it, there was a broken link I changed 

**old links**
https://emojipedia-us.s3.amazonaws.com/source/microsoft-teams/337/skull_1f480.png
https://emojipedia-us.s3.amazonaws.com/source/microsoft-teams/337/skull-and-crossbones_2620-fe0f.png
https://emojipedia-us.s3.amazonaws.com/source/microsoft-teams/337/ghost_1f47b.png

**new links**
https://www.imagenspng.com.br/wp-content/uploads/2022/11/emoji-png-0105.png
https://www.imagenspng.com.br/wp-content/uploads/2022/11/emoji-png-0106.png
https://www.imagenspng.com.br/wp-content/uploads/2022/11/emoji-png-0111.png

now it is working, I will fix the other ones
![image](https://github.com/Diptenusarkar/Website-Template/assets/16242029/f88a80ee-00f8-408a-94f9-4d65ecbc589c)

**Comment by Diptenusarkar** [comment]
Thank You your PR.
