### ISSUE TITLE
Resume Builder

### ISSUE THREAD

**Issue by rittikadeb** [Diptenusarkar/Website-Template#369]
##Description

A Resume Builder is a web-based application that simplifies the process of crafting a well-designed resume by providing an intuitive and user-friendly interface. 

### Tech Stack Used

- HTML
- CSS
- JavaScript
- PHP

**Comment by slaughterhectic** [comment]
I have already made a pull request it was my

**Comment by slaughterhectic** [comment]
project please look at it
