### ISSUE TITLE
Make a dark mode toggle switch template

### ISSUE THREAD

**Issue by ElvinPero** [Diptenusarkar/Website-Template#49]
Night mode is needed for most sites

**Comment by ElvinPero** [comment]
@Diptenusarkar kindly assign this one to me I can make a template

**Comment by Diptenusarkar** [comment]
Best of luck 🤞 See you soon with your Code ☺️

**Comment by JakubPristas** [comment]
Can you assign this to me ?

**Comment by JakubPristas** [comment]
Yeah, i take a look.

**Comment by ElvinPero** [comment]
@Diptenusarkar I have submitted my PR 😇

**Comment by Diptenusarkar** [comment]
Thank You for Submitting Your PR I need some time to check.

**Comment by ElvinPero** [comment]
@Diptenusarkar Also please mark this as hacktoberfest

**Comment by Diptenusarkar** [comment]
Sure @ElvinPero 
Don't Worry.
