### ISSUE TITLE
BOOKING TEMPLATE

### ISSUE THREAD

**Issue by ritviz344** [Diptenusarkar/Website-Template#57]
Hey @Diptenusarkar , i want to add a online booking template to this repo . kindly assign this issue to me and considered it for my HACKTOBERFEST2022 PR. 
![Pricing - pure css - #16 and 85 more pages - Personal 2 - Microsoft​ Edge 11-10-2022 08_39_49 (2)](https://user-images.githubusercontent.com/55100068/194988370-b2cc07fc-d1b4-4e99-9192-2455fe8c73b7.png)

**Comment by Diptenusarkar** [comment]
Best Of luck 🤞
