### ISSUE TITLE
Add Montserrat text-style to Applanding index.html page.

### ISSUE THREAD

**Issue by aksharma27** [Diptenusarkar/Website-Template#60]
**Is your feature request related to a problem? Please describe.**
The index.html has normal font style, which kind of look a bit old styled.

**Describe the solution you'd like**
I will just import montserrat style from google fonts and apply in the html of index.html of landing page folder.

**Describe alternatives you've considered**
If montserrat won't work, I would look for any other style if possible.

**Additional context**

###This is how it would look:
![Screenshot (132)](https://user-images.githubusercontent.com/83135634/194994960-8e45f41c-ff04-4afb-896e-91f49ba7e511.png)

**Comment by Diptenusarkar** [comment]
Sure, Go ahead.
