### ISSUE TITLE
Domain shell template is not mobile responsive 

### ISSUE THREAD

**Issue by thecodermaniac** [Diptenusarkar/Website-Template#61]
![image](https://user-images.githubusercontent.com/79108244/195009260-e2ec3daf-90ac-4fbe-9c5b-5edb56403d73.png)

assign me this issue so that i can work on it

**Comment by Diptenusarkar** [comment]
Best of luck 🤞

**Comment by thecodermaniac** [comment]
https://github.com/Diptenusarkar/Website-Template/pull/73  pls merge @Diptenusarkar
