### ISSUE TITLE
news template 1 is not mobile responsive 

### ISSUE THREAD

**Issue by thecodermaniac** [Diptenusarkar/Website-Template#62]
![image](https://user-images.githubusercontent.com/79108244/195010479-e4955b6b-8436-4bf1-9059-58d84fa0ff4e.png)

assign me this issue

**Comment by Diptenusarkar** [comment]
Best of luck 🤞

**Comment by thecodermaniac** [comment]
https://github.com/Diptenusarkar/Website-Template/pull/91 pls merge with hacktoberfest tag @Diptenusarkar
