### ISSUE TITLE
navbar not responsive in sticky navbar template 

### ISSUE THREAD

**Issue by thecodermaniac** [Diptenusarkar/Website-Template#63]
![image](https://user-images.githubusercontent.com/79108244/195010941-5922dc68-c860-4775-a5d9-465d9f5a3e24.png)

assign me i will work on it

**Comment by Diptenusarkar** [comment]
Best of luck 🤞

**Comment by thecodermaniac** [comment]
https://github.com/Diptenusarkar/Website-Template/pull/71 merge the PR with hactoberfest tag ;)
