### ISSUE TITLE
Portfolio -> index.html -> anchor icons rotate 360 deg when hovered

### ISSUE THREAD

**Issue by aksharma27** [Diptenusarkar/Website-Template#87]
###   Feature Request

**Is your feature request related to a problem? Please describe.**
When the anchor icons are hovered, the icons will rotate to 360 deg with a transition of 1.45 s, If you want the transition timing to be less please comment I will change it.

Can I work on this issue?

**Comment by Diptenusarkar** [comment]
So you are going to change transition time ?

**Comment by aksharma27** [comment]
> So you are going to change transition time ?

No, if you want to change I can change, but the main change that I have proposed is : transformation of social icons when hovered, they will rotate 360 degrees.
