### ISSUE TITLE
Theme clock

### ISSUE THREAD

**Issue by sanil011** [Diptenusarkar/Website-Template#97]
I would like to add a Theme Clock.

This can be use by anyone one to use in their project or take inspiration

A clock made using CSS and also show correct time with the help of some javascript line of code.

Also have a button that can make transition from dark theme to light theme or light theme to dark theme.
<img width="1440" alt="theme clock" src="https://user-images.githubusercontent.com/105095685/195401526-f9597bc3-022f-4714-9a2d-2ca7e20fb97d.png">

please assign me this

**Comment by Diptenusarkar** [comment]
Best of luck 🤞
